#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
文档质量检查脚本 v1.1
全面检查生成的 Word 文档，覆盖以下维度：

1. 字体检查 — 检测正文/标题是否使用了非预期字体
2. 段落格式检查 — 行距、首行缩进、段前段后间距是否符合模板
3. 编号冗余检查 — 检测标题中是否残留编号文本（与模板自动编号冲突）
4. AIGC 标识检查 — 区分「系统注入水印（正常）」和「AI 痕迹（警告）」

用法:
    python doc_quality_check.py <文档.docx> [--template <模板.docx>]
    python doc_quality_check.py <文档.docx>  # 无模板，使用默认规范
"""

import sys
import os
import re
import zipfile
from docx import Document
from docx.shared import Pt, Cm
from docx.oxml.ns import qn


# ============================================================
# AIGC 标识规则
# ============================================================

# 系统注入的 AIGC 水印模式（合规要求，不可删除，检测时标注为「正常」）
SYSTEM_WATERMARK_PATTERN = re.compile(
    r'AIGC标识\s*[:：]\s*[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
    re.IGNORECASE
)

AIGC_PATTERNS = {
    # --- AIGC 声明文本（排除系统水印的 AIGC标识: 前缀）---
    'aigc_label': {
        'pattern': r'(?<!标识[:\s])\bAIGC\b|AI生成|AI撰写|AI辅助生成|人工智能生成|由AI生成',
        'label': 'AIGC 声明文本 (如 "AI生成""AIGC" 等)',
        'category': '声明文本',
    },

    # --- python-docx 痕迹 ---
    'python_docx_meta': {
        'pattern': r'python-docx|generated by python',
        'label': 'python-docx 生成痕迹 (core.xml 中的标识)',
        'category': '生成工具',
    },

    # --- AI 写作模式特征词 ---
    'ai_fillers': {
        'pattern': r'值得注意的是|需要指出的是|不言而喻|毋庸置疑|显而易见|毋庸置疑地|总而言之|综上所述(?!.*)',
        'label': 'AI 高频填充词 (如 "值得注意的是""不言而喻" 等)',
        'category': 'AI 特征词',
    },

    # --- AI 对称结构 ---
    'ai_parallel': {
        'pattern': r'不仅.{2,20}而且.{2,20}还.{2,20}',
        'label': 'AI 对称从句 (不仅…而且…还…)',
        'category': 'AI 结构模式',
    },

    # --- AI 夸大象征 ---
    'ai_grandiose': {
        'pattern': r'标志着|见证了|彰显了|昭示着|诠释着|展现了.{0,5}魅力|迈向.{0,5}新台阶|开启.{0,5}新篇章|谱写.{0,5}新篇章',
        'label': 'AI 夸大象征表达 (如 "标志着""见证了""迈向新台阶")',
        'category': 'AI 夸大表达',
    },

    # --- AI 煽情结尾 ---
    'ai_ending': {
        'pattern': r'未来光明|激动人心|令人振奋|意义深远|任重道远|砥砺前行|乘风破浪',
        'label': 'AI 煽情结尾词 (如 "未来光明""砥砺前行")',
        'category': 'AI 煽情表达',
    },

    # --- 通用积极结论 ---
    'generic_conclusion': {
        'pattern': r'将[为能].*带来.*提升|实现.*跨越式发展|打造.*标杆|构建.*生态',
        'label': '通用积极结论 (如 "将为…带来提升""实现跨越式发展")',
        'category': '通用套话',
    },

    # --- 语言混杂（默认禁用，专业术语如 AES/PDCA 会误报） ---
    # 'mixed_en': {
    #     'pattern': r'[\u4e00-\u9fff][a-zA-Z]{3,}|[a-zA-Z]{3,}[\u4e00-\u9fff]',
    #     'label': '中文段落中混入英文单词 (连续3+字母)',
    #     'category': '语言混杂',
    # },
}


# ============================================================
# 检查函数
# ============================================================

def check_fonts(doc, template_doc=None):
    """检查字体是否符合预期"""
    issues = []
    expected_font = '宋体'

    # 如果有模板，提取模板预期字体
    if template_doc:
        for style in template_doc.styles:
            if style.name == 'Normal' and style.font.name:
                expected_font = style.font.name
                break

    for i, para in enumerate(doc.paragraphs):
        if not para.text.strip():
            continue
        for run in para.runs:
            if not run.text.strip():
                continue
            # 检查 run 级字体
            run_font = run.font.name
            if run_font and run_font != expected_font:
                # 检查东亚字体
                rPr = run._element.find(qn('w:rPr'))
                if rPr is not None:
                    rFonts = rPr.find(qn('w:rFonts'))
                    if rFonts is not None:
                        east = rFonts.get(qn('w:eastAsia'))
                        if east and east != expected_font:
                            issues.append({
                                'type': '字体偏差',
                                'para_idx': i,
                                'text': para.text[:40],
                                'detail': f'东亚字体={east}, 预期={expected_font}',
                                'severity': 'warning',
                            })

    return issues


def check_paragraph_format(doc, template_doc=None):
    """检查段落格式"""
    issues = []

    # 预期格式（来自模板或默认值）
    expected_line_spacing = 1.5
    expected_indent_cm = 0.74

    if template_doc:
        for style in template_doc.styles:
            if style.name in ('正文1', '正文', 'Normal'):
                pf = style.paragraph_format
                if pf.line_spacing:
                    expected_line_spacing = pf.line_spacing
                if pf.first_line_indent:
                    expected_indent_cm = round(pf.first_line_indent.cm, 2)
                if style.name in ('正文1', '正文'):
                    break  # 优先正文1

    for i, para in enumerate(doc.paragraphs):
        if not para.text.strip():
            continue
        pf = para.paragraph_format
        is_heading = para.style and para.style.name.startswith('Heading')

        # 正文段落：检查行距
        if not is_heading and pf.line_spacing:
            ls = pf.line_spacing
            if isinstance(ls, float) and abs(ls - expected_line_spacing) > 0.1:
                issues.append({
                    'type': '行距偏差',
                    'para_idx': i,
                    'text': para.text[:40],
                    'detail': f'行距={ls}, 预期={expected_line_spacing}',
                    'severity': 'warning',
                })

        # 正文段落：检查首行缩进
        if not is_heading and pf.first_line_indent:
            indent_cm = round(pf.first_line_indent.cm, 2)
            if abs(indent_cm - expected_indent_cm) > 0.05:
                issues.append({
                    'type': '首行缩进偏差',
                    'para_idx': i,
                    'text': para.text[:40],
                    'detail': f'缩进={indent_cm}cm, 预期={expected_indent_cm}cm',
                    'severity': 'warning',
                })

        # Heading 段落：检查是否有冗余首行缩进
        if is_heading and pf.first_line_indent is not None:
            indent_cm = round(pf.first_line_indent.cm, 2) if pf.first_line_indent else 0
            if indent_cm > 0:
                issues.append({
                    'type': '标题冗余缩进',
                    'para_idx': i,
                    'text': para.text[:40],
                    'detail': f'Heading 有首行缩进={indent_cm}cm，应为0',
                    'severity': 'error',
                })

        # Heading 段落：检查 run 级冗余字号
        if is_heading:
            for run in para.runs:
                if run.font.size is not None:
                    issues.append({
                        'type': 'Heading run冗余字号',
                        'para_idx': i,
                        'text': para.text[:40],
                        'detail': f'run.font.size={run.font.size.pt}pt, 应由样式继承',
                        'severity': 'warning',
                    })
                    break

    return issues


def check_numbering_redundancy(doc):
    """检查编号冗余：标题中是否残留编号文本"""
    issues = []

    # 编号文本模式（与 strip_heading_number 对应）
    number_patterns = [
        (r'^[一二三四五六七八九十百千]+[、．.．]\s*', '中文数字编号'),
        (r'^\d+(?:\.\d+)*[.．、]?\s+', '十进制编号'),
        (r'^[（(]\d+[）)]\s*', '括号编号'),
    ]

    for i, para in enumerate(doc.paragraphs):
        if not (para.style and para.style.name.startswith('Heading')):
            continue
        text = para.text.strip()
        if not text:
            continue

        for pattern, label in number_patterns:
            if re.match(pattern, text):
                issues.append({
                    'type': '标题编号冗余',
                    'para_idx': i,
                    'text': text[:50],
                    'detail': f'标题含{label}，模板自动编号会叠加',
                    'severity': 'error',
                })
                break

    # 检查段落级 numPr 冗余
    for i, para in enumerate(doc.paragraphs):
        pPr = para._element.find(qn('w:pPr'))
        if pPr is not None:
            numPr = pPr.find(qn('w:numPr'))
            if numPr is not None:
                # Heading 样式已有 numPr，段落级再设就是冗余
                if para.style and para.style.name.startswith('Heading'):
                    numId_el = numPr.find(qn('w:numId'))
                    numId = numId_el.get(qn('w:val')) if numId_el is not None else '?'
                    issues.append({
                        'type': '段落级numPr冗余',
                        'para_idx': i,
                        'text': para.text[:40],
                        'detail': f'Heading 已有样式级 numPr，段落级 numId={numId} 冗余',
                        'severity': 'warning',
                    })

    return issues


def _check_custom_xml_aigc(docx_path):
    """检查 docProps/custom.xml 中的 AIGC 自定义属性"""
    issues = []
    try:
        with zipfile.ZipFile(docx_path, 'r') as zf:
            if 'docProps/custom.xml' in zf.namelist():
                content = zf.read('docProps/custom.xml').decode('utf-8', errors='ignore')
                if 'AIGC' in content:
                    issues.append({
                        'type': 'AIGC水印 [系统注入]',
                        'para_idx': -1,
                        'text': '(文档属性 docProps/custom.xml)',
                        'detail': 'docProps/custom.xml 含 AIGC 自定义属性，系统合规水印，不可删除',
                        'severity': 'info',
                        'category': '系统注入',
                    })
    except Exception:
        pass
    return issues


def check_aigc_identifiers(doc, docx_path=None):
    """检查 AIGC 标识 — 区分系统注入水印（正常）和 AI 痕迹（警告）"""
    issues = []

    for i, para in enumerate(doc.paragraphs):
        text = para.text
        if not text.strip():
            continue

        # 1. 优先检查系统注入的 AIGC 水印（AIGC标识: <UUID>）
        if SYSTEM_WATERMARK_PATTERN.search(text):
            # 检查是否为隐藏文本（<w:vanish/>）
            is_hidden = False
            for run in para.runs:
                rPr = run._element.find(qn('w:rPr'))
                if rPr is not None and rPr.find(qn('w:vanish')) is not None:
                    is_hidden = True
                    break

            issues.append({
                'type': 'AIGC水印 [系统注入]',
                'para_idx': i,
                'text': text[:50],
                'detail': f'系统合规水印{"，隐藏文本" if is_hidden else ""}，自动注入，不可删除',
                'severity': 'info',
                'category': '系统注入',
            })
            continue  # 系统水印段落不再检查其他 AIGC 规则

        # 2. 检查 AI 痕迹规则（AI 味词、python-docx 痕迹等）
        for rule_name, rule in AIGC_PATTERNS.items():
            matches = list(re.finditer(rule['pattern'], text))
            if matches:
                for m in matches:
                    matched_text = m.group()
                    issues.append({
                        'type': f'AIGC痕迹 [{rule["label"]}]',
                        'para_idx': i,
                        'text': text[:50],
                        'detail': f'匹配: "{matched_text}" (规则: {rule_name})',
                        'severity': 'error' if rule['category'] in ('声明文本',) else 'warning',
                        'category': rule['category'],
                    })

    # 3. 检查文档元数据（python-docx 作者）
    try:
        core_props = doc.core_properties
        if core_props.author and 'python' in core_props.author.lower():
            issues.append({
                'type': 'AIGC痕迹 [python-docx 作者]',
                'para_idx': -1,
                'text': '(文档属性)',
                'detail': f'author={core_props.author}',
                'severity': 'warning',
                'category': '生成工具',
            })
    except:
        pass

    # 4. 检查 docProps/custom.xml 中的 AIGC 属性
    if docx_path:
        issues.extend(_check_custom_xml_aigc(docx_path))

    return issues


# ============================================================
# 主函数
# ============================================================

def run_check(docx_path, template_path=None):
    """执行全面质量检查"""
    print(f'检查文档: {docx_path}')
    if template_path:
        print(f'参考模板: {template_path}')
    print()

    doc = Document(docx_path)
    template_doc = Document(template_path) if template_path and os.path.exists(template_path) else None

    all_issues = []

    # 1. 字体检查
    print('--- 1. 字体检查 ---')
    font_issues = check_fonts(doc, template_doc)
    all_issues.extend(font_issues)
    print(f'  发现 {len(font_issues)} 个问题')

    # 2. 段落格式检查
    print('--- 2. 段落格式检查 ---')
    fmt_issues = check_paragraph_format(doc, template_doc)
    all_issues.extend(fmt_issues)
    print(f'  发现 {len(fmt_issues)} 个问题')

    # 3. 编号冗余检查
    print('--- 3. 编号冗余检查 ---')
    num_issues = check_numbering_redundancy(doc)
    all_issues.extend(num_issues)
    print(f'  发现 {len(num_issues)} 个问题')

    # 4. AIGC 标识检查（区分系统注入和 AI 痕迹）
    print('--- 4. AIGC 标识检查（系统水印=正常 / AI痕迹=警告） ---')
    aigc_issues = check_aigc_identifiers(doc, docx_path)
    all_issues.extend(aigc_issues)
    system_count = len([i for i in aigc_issues if i.get('severity') == 'info'])
    warning_count = len([i for i in aigc_issues if i.get('severity') != 'info'])
    print(f'  发现 {system_count} 个系统水印（正常）, {warning_count} 个 AI 痕迹')

    # 汇总
    print()
    print('=' * 60)
    errors = [i for i in all_issues if i.get('severity') == 'error']
    warnings = [i for i in all_issues if i.get('severity') == 'warning']
    infos = [i for i in all_issues if i.get('severity') == 'info']
    print(f'检查结果: {len(errors)} 个错误, {len(warnings)} 个警告, {len(infos)} 个系统水印（正常）')

    if all_issues:
        print()
        # 按严重度排序：error > warning > info
        for issue in errors + warnings + infos:
            if issue['severity'] == 'error':
                icon = '✗'
            elif issue['severity'] == 'warning':
                icon = '⚠'
            else:
                icon = 'ℹ'
            print(f'  {icon} [{issue["type"]}] 段落{issue["para_idx"]}: {issue["text"]}')
            print(f'     → {issue["detail"]}')
    else:
        print('  全部通过！')

    # 返回时排除 info 级别（系统水印不算问题）
    return [i for i in all_issues if i.get('severity') != 'info']


def main():
    if len(sys.argv) < 2:
        print('用法: python doc_quality_check.py <文档.docx> [--template <模板.docx>]')
        sys.exit(1)

    docx_path = sys.argv[1]
    template_path = None

    args = sys.argv[2:]
    i = 0
    while i < len(args):
        if args[i] == '--template' and i + 1 < len(args):
            template_path = args[i + 1]
            i += 2
        else:
            i += 1

    issues = run_check(docx_path, template_path)
    sys.exit(0 if not issues else 1)


if __name__ == '__main__':
    main()
